import { useEffect, useState } from "react";
import { LineChart } from "lucide-react";
import { EmptyState } from "../components/ui/EmptyState";
import { Badge } from "../components/ui/Badge";
import { api } from "../services/api";
import type { Experiment, ExperimentSummary } from "../types";

const METRIC_KEYS = ["relevance", "completeness", "consistency", "format_adherence"] as const;

export default function Evaluations() {
  const [summaries, setSummaries] = useState<ExperimentSummary[] | null>(null);
  const [details, setDetails] = useState<Record<string, Experiment>>({});

  useEffect(() => {
    api.listExperiments().then(async (list) => {
      setSummaries(list);
      const entries = await Promise.all(
        list.slice(0, 20).map(async (s) => [s.id, await api.getExperiment(s.id)] as const)
      );
      setDetails(Object.fromEntries(entries));
    });
  }, []);

  const rows = Object.values(details).flatMap((exp) =>
    exp.runs
      .filter((r) => r.evaluation)
      .map((r) => ({ experimentName: exp.name, run: r }))
  );

  return (
    <div className="mx-auto max-w-5xl px-8 py-6">
      <div className="mb-5">
        <h1 className="text-lg font-semibold tracking-tight text-ink">Evaluations</h1>
        <p className="mt-0.5 text-sm text-ink-muted">
          Evaluation scores across every experiment run, using PromptLab's transparent rule-based
          evaluator.
        </p>
      </div>

      {summaries && summaries.length === 0 && (
        <EmptyState
          icon={LineChart}
          title="No evaluations yet"
          description="Evaluation results appear here automatically once you run an experiment."
        />
      )}

      {rows.length > 0 && (
        <div className="overflow-x-auto rounded-md border border-border bg-surface">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-border bg-zinc-50 text-left text-xs font-medium text-ink-muted">
                <th className="px-4 py-2">Experiment</th>
                <th className="px-4 py-2">Run</th>
                {METRIC_KEYS.map((k) => (
                  <th key={k} className="px-4 py-2 capitalize">
                    {k.replace("_", " ")}
                  </th>
                ))}
                <th className="px-4 py-2">Overall</th>
              </tr>
            </thead>
            <tbody>
              {rows.map(({ experimentName, run }) => (
                <tr key={run.id} className="border-b border-border last:border-b-0">
                  <td className="px-4 py-2 text-ink-muted">{experimentName}</td>
                  <td className="px-4 py-2 text-ink">{run.label}</td>
                  {METRIC_KEYS.map((k) => (
                    <td key={k} className="px-4 py-2 text-ink">
                      {run.evaluation?.metrics[k]?.score ?? <span className="text-ink-faint">—</span>}
                    </td>
                  ))}
                  <td className="px-4 py-2 font-medium text-ink">
                    {run.evaluation?.overall_score ?? "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <div className="mt-4 flex items-center gap-2 text-xs text-ink-faint">
        <Badge tone="neutral">Rule-based</Badge>
        Scores are computed from measurable properties of each response (term overlap, length,
        structural validity) — not generated by an LLM judge.
      </div>
    </div>
  );
}
